require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/armies", type: :request do
  let(:user) { create(:user) }
  let(:game_system) { create(:game_system) }
  # This should return the minimal set of attributes required to create a valid
  # Army. As you add validations to Army, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      user_id: user.id,
      name: "Test Army",
      game_system_id: game_system.id
    }
  }

  let(:invalid_attributes) {
    {
      user_id: nil,
      name: "Test Army",
      game_system_id: game_system.id
    }
  }

  before do
    sign_in(user)
  end

  describe "GET /index" do
    it "renders a successful response" do
      Army.create! valid_attributes
      get armies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      army = Army.create! valid_attributes
      get army_url(army)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_army_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      army = Army.create! valid_attributes
      get edit_army_url(army)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Army" do
        expect {
          post armies_url, params: {army: valid_attributes}
        }.to change(Army, :count).by(1)
      end

      it "redirects to the created army" do
        post armies_url, params: {army: valid_attributes}
        expect(response).to redirect_to(army_url(Army.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Army" do
        expect {
          post armies_url, params: {army: invalid_attributes}
        }.to change(Army, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post armies_url, params: {army: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "New Name"
        }
      }

      it "updates the requested army" do
        army = Army.create! valid_attributes
        patch army_url(army), params: {army: new_attributes}
        army.reload
        expect(army.name).to eq("New Name")
      end

      it "redirects to the army" do
        army = Army.create! valid_attributes
        patch army_url(army), params: {army: new_attributes}
        army.reload
        expect(response).to redirect_to(army_url(army))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        army = Army.create! valid_attributes
        patch army_url(army), params: {army: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested army" do
      army = Army.create! valid_attributes
      expect {
        delete army_url(army)
      }.to change(Army, :count).by(-1)
    end

    it "redirects to the armies list" do
      army = Army.create! valid_attributes
      delete army_url(army)
      expect(response).to redirect_to(armies_url)
    end
  end
end
