require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/army_lists", type: :request do
  let(:user) { create(:user) }
  let(:army) { create(:army, user:) }

  let(:valid_attributes) {
    {
      army_id: army.id,
      name: "Army List"
    }
  }

  let(:invalid_attributes) {
    {
      army_id: nil
    }
  }

  before do
    sign_in(user)
  end

  describe "GET /index" do
    it "renders a successful response" do
      ArmyList.create! valid_attributes
      get army_army_lists_url(army)
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      army_list = ArmyList.create! valid_attributes
      get army_army_list_url(army, army_list)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_army_army_list_url(army)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      army_list = ArmyList.create! valid_attributes
      get edit_army_army_list_url(army, army_list)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ArmyList" do
        expect {
          post army_army_lists_url(army), params: {army_list: valid_attributes}
        }.to change(ArmyList, :count).by(1)
      end

      it "redirects to the created army_list" do
        post army_army_lists_url(army), params: {army_list: valid_attributes}
        expect(response).to redirect_to(army_army_list_url(army, ArmyList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ArmyList" do
        expect {
          post army_army_lists_url(army), params: {army_list: invalid_attributes}
        }.to change(ArmyList, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post army_army_lists_url(army), params: {army_list: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "New Name"
        }
      }

      it "updates the requested army_list" do
        army_list = ArmyList.create! valid_attributes
        patch army_army_list_url(army, army_list), params: {army_list: new_attributes}
        army_list.reload
        expect(army_list.name).to eq("New Name")
      end

      it "redirects to the army_list" do
        army_list = ArmyList.create! valid_attributes
        patch army_army_list_url(army, army_list), params: {army_list: new_attributes}
        army_list.reload
        expect(response).to redirect_to(army_army_list_url(army, army_list))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        army_list = ArmyList.create! valid_attributes
        patch army_army_list_url(army, army_list), params: {army_list: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested army_list" do
      army_list = ArmyList.create! valid_attributes
      expect {
        delete army_army_list_url(army, army_list)
      }.to change(ArmyList, :count).by(-1)
    end

    it "redirects to the army_lists list" do
      army_list = ArmyList.create! valid_attributes
      delete army_army_list_url(army, army_list)
      expect(response).to redirect_to(army_url(army))
    end
  end
end
