require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/games", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Game. As you add validations to Game, be sure to
  # adjust the attributes here as well.
  let(:gaming_session) { create(:gaming_session) }
  let(:game_system) { create(:wargame, :turn_based) }
  let(:new_game_system) { create(:game_system) }
  let(:user) { create(:user) }
  let(:user2) { create(:user) }
  let(:valid_attributes) {
    {
      gaming_session_id: gaming_session.id,
      game_system_id: game_system.id,
      players_attributes: [
        {controller_id: user.id, controller_type: "User"},
        {controller_id: user2.id, controller_type: "User"}
      ]
    }
  }

  let(:invalid_attributes) {
    {
      gaming_session_id: nil,
      game_system_id: nil
    }
  }

  before do
    sign_in(user)
    allow_any_instance_of(GamesController).to receive(:current_user).and_return(user)
  end

  describe "GET /index" do
    it "renders a successful response" do
      Game.create! valid_attributes
      get games_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      game = Game.create! valid_attributes
      get game_url(game)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_game_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      game = Game.create! valid_attributes
      get edit_game_url(game)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Game" do
        expect {
          post games_url, params: {game: valid_attributes}
        }.to change(Game, :count).by(1)
      end

      it "redirects to the created game" do
        post games_url, params: {game: valid_attributes}
        expect(response).to redirect_to(Game.last)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Game" do
        expect {
          post games_url, params: {game: invalid_attributes}
        }.to change(Game, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post games_url, params: {game: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          game_system_id: new_game_system.id
        }
      }

      it "updates the requested game" do
        game = Game.create! valid_attributes
        patch game_url(game), params: {game: new_attributes}
        game.reload
        expect(game.game_system).to eq(new_game_system)
      end

      it "should upate player data" do
        game = Game.create! valid_attributes
        player = game.players.first
        data = [{
          id: player.id,
          game_data: {
            turns: [
              {primary: 5, seconday: 10},
              {primary: 20, seconday: 10}
            ]
          }
        }]
        patch game_url(game), params: {game: {players_attributes: data}}
        player.reload
        expect(player.game_data["turns"].first["primary"]).to eq("5")
        expect(player.game_data["turns"].second["primary"]).to eq("20")
      end

      it "redirects to the game" do
        game = Game.create! valid_attributes
        patch game_url(game), params: {game: new_attributes}
        game.reload
        expect(response).to redirect_to(game_url(game))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        game = Game.create! valid_attributes
        patch game_url(game), params: {game: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested game" do
      game = Game.create! valid_attributes
      expect {
        delete game_url(game)
      }.to change(Game, :count).by(-1)
    end

    it "redirects to the games list" do
      game = Game.create! valid_attributes
      session = game.gaming_session
      delete game_url(game)
      expect(response).to redirect_to(session)
    end
  end
end
