require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/gaming_groups", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # GamingGroup. As you add validations to GamingGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: "test group"
    }
  }

  let(:invalid_attributes) {
    {
      name: nil
    }
  }

  before do
    sign_in create(:user)
  end

  describe "GET /index" do
    it "renders a successful response" do
      GamingGroup.create! valid_attributes
      get gaming_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      gaming_group = GamingGroup.create! valid_attributes
      get gaming_group_url(gaming_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_gaming_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      gaming_group = GamingGroup.create! valid_attributes
      get edit_gaming_group_url(gaming_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GamingGroup" do
        expect {
          post gaming_groups_url, params: {gaming_group: valid_attributes}
        }.to change(GamingGroup, :count).by(1)
      end

      it "redirects to the created gaming_group" do
        post gaming_groups_url, params: {gaming_group: valid_attributes}
        expect(response).to redirect_to(gaming_group_url(GamingGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GamingGroup" do
        expect {
          post gaming_groups_url, params: {gaming_group: invalid_attributes}
        }.to change(GamingGroup, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post gaming_groups_url, params: {gaming_group: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "Other name"
        }
      }

      it "updates the requested gaming_group" do
        gaming_group = GamingGroup.create! valid_attributes
        patch gaming_group_url(gaming_group), params: {gaming_group: new_attributes}
        gaming_group.reload
        expect(gaming_group.name).to eq("Other name")
      end

      it "redirects to the gaming_group" do
        gaming_group = GamingGroup.create! valid_attributes
        patch gaming_group_url(gaming_group), params: {gaming_group: new_attributes}
        gaming_group.reload
        expect(response).to redirect_to(gaming_group_url(gaming_group))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        gaming_group = GamingGroup.create! valid_attributes
        patch gaming_group_url(gaming_group), params: {gaming_group: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested gaming_group" do
      gaming_group = GamingGroup.create! valid_attributes
      expect {
        delete gaming_group_url(gaming_group)
      }.to change(GamingGroup, :count).by(-1)
    end

    it "redirects to the gaming_groups list" do
      gaming_group = GamingGroup.create! valid_attributes
      delete gaming_group_url(gaming_group)
      expect(response).to redirect_to(gaming_groups_url)
    end
  end
end
