default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: <%= ENV.fetch("USER") %>
  database: "aic-dev"

test:
  <<: *default
  username: <%= ENV.fetch("USER", "postgres") %>
  database: "aic-test"

production:
  <<: *default
