default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", 'localhost') %>
  username: postgres
  password: <%= ENV.fetch("DB_PASSWORD", '') %>
  database: gaming_night_tracker

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", 'localhost') %>
  username: postgres
  password: <%= ENV.fetch("DB_PASSWORD", '') %>
  database: gaming_night_tracker_test

production:
  <<: *default
